### ISSUE TITLE
dependency texlive-latex-extra, add to install docs

### ISSUE THREAD

**Issue by evelynmitchell** [a3n/miki#2]
Needed to resolve:
LaTeX Error: Command \textquotesingle unavailable in encoding T1.
on Ubuntu 16.04
following the discussion at
https://github.com/jgm/pandoc/issues/2439

Adding that package to the install list is the solution.

**Comment by a3n** [comment]
Thanks very much.
Updated README.rst.
Please see that, and the commit.

**Comment by a3n** [comment]
Closing as fixed. Thanks very much for the report, and the fix.
